### ISSUE TITLE
Not able to set boundry for bottom and top

### ISSUE THREAD

**Issue by bajrang87** [3DGenomes/ngx-resizable#15]
I need to restrict user should not able to resize extreme end of browser window, we should be able to set some margin around 100px from bottom of screen, similarly on top as well. So user will not be able to go beyond screen of bottom and top. Please provide a way if we have any mechanism to set it.

Thanks,
Bajrang

**Comment by TheMelmacian** [comment]
I know it is over a year since this question was asked but I started to use ngx-resizable only recently and solved this problem with simple css.

Based on the official example with 4x4 cells with the default layout:
```css
.content {
    height: 100vh;
}
.row {
    min-height: 100px;
    max-height: calc(100vh - 100px);
}
.cell {
    min-width: 100px;
    max-width: calc(100vw - 100px);
}
```
For the column layout you have to switch the rules for cells and rows.
